In [1]:
import pandas as pd
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

print("NLTK resources downloaded successfully!")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...

NLTK resources downloaded successfully!

[nltk_data]   Package punkt_tab is already up-to-date!

In [3]:
df = pd.read_csv("IMDB_Dataset_Cleaned.csv")

print("Dataset loaded successfully!")
print("Number of reviews:", len(df))

df.head()

Dataset loaded successfully!
Number of reviews: 49396

                                              review sentiment
0  $25,000 Pyramid Clues: Deep Blue Sea. Tremors....  negative
1  0.5/10. This movie has absolutely nothing good...  negative
2  0*'s Christian Slater, Tara Reid, Stephen Dorf...  negative
3  102 Dalmatians (2000, Dir. Kevin Lima) <br /><...  negative
4  102 DALMATIANS [Walt Disney]: I wasn't a fan o...  negative

In [4]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Dataset Shape:
(49396, 2)

Column Names:
['review', 'sentiment']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49396 entries, 0 to 49395
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     49396 non-null  object
 1   sentiment  49396 non-null  object
dtypes: object(2)
memory usage: 771.9+ KB

In [5]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
review       0
sentiment    0
dtype: int64

In [6]:
df = df.dropna(subset=["review"])

print("Missing reviews removed.")
print("Remaining reviews:", len(df))

Missing reviews removed.
Remaining reviews: 49396

In [7]:
duplicate_count = df["review"].duplicated().sum()

print("Number of duplicate reviews:", duplicate_count)

Number of duplicate reviews: 0

In [8]:
df = df.drop_duplicates(subset=["review"])

print("Duplicates removed.")
print("Reviews remaining:", len(df))

Duplicates removed.
Reviews remaining: 49396

In [9]:
def clean_text(text):
    
    # Convert text to string
    text = str(text)
    
    # 1. Convert to lowercase
    text = text.lower()
    
    # 2. Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)
    
    # 3. Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    
    # 4. Remove numbers
    text = re.sub(r'\d+', ' ', text)
    
    # 5. Remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )
    
    # 6. Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    
    # 7. Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text


print("Cleaning function created successfully!")

Cleaning function created successfully!

In [10]:
sample_text = "This movie was AMAZING!!! Visit https://example.com <br> It was 100% great."

cleaned_sample = clean_text(sample_text)

print("Original:")
print(sample_text)

print("\nCleaned:")
print(cleaned_sample)

Original:
This movie was AMAZING!!! Visit https://example.com <br> It was 100% great.

Cleaned:
this movie was amazing visit it was great

In [11]:
stop_words = set(stopwords.words('english'))

stemmer = PorterStemmer()

print("Number of English stopwords:", len(stop_words))
print("Stemmer initialized successfully!")

Number of English stopwords: 198
Stemmer initialized successfully!

In [12]:
def preprocess_review(text):
    
    # Convert to string
    text = str(text)
    
    # --------------------------------
    # TEXT CLEANING
    # --------------------------------
    
    # Lowercase
    text = text.lower()
    
    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)
    
    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    
    # Remove numbers
    text = re.sub(r'\d+', ' ', text)
    
    # Remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )
    
    # Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # --------------------------------
    # TOKENIZATION
    # --------------------------------
    
    tokens = word_tokenize(text)
    
    # --------------------------------
    # STOPWORD REMOVAL
    # --------------------------------
    
    tokens = [
        word for word in tokens
        if word not in stop_words
    ]
    
    # --------------------------------
    # STEMMING
    # --------------------------------
    
    tokens = [
        stemmer.stem(word)
        for word in tokens
    ]
    
    # Convert tokens back to text
    cleaned_text = ' '.join(tokens)
    
    return cleaned_text


print("Preprocessing function created successfully!")

Preprocessing function created successfully!

In [13]:
sample = "This movie was AMAZING!!! I really loved watching it."

print("Original:")
print(sample)

print("\nProcessed:")
print(preprocess_review(sample))

Original:
This movie was AMAZING!!! I really loved watching it.

Processed:
movi amaz realli love watch

In [14]:
print("Processing all reviews...")

df["cleaned_review"] = df["review"].apply(preprocess_review)

print("All reviews processed successfully!")

Processing all reviews...
All reviews processed successfully!

In [15]:
df.head()

,review,sentiment,cleaned_review
0,"$25,000 Pyramid Clues: Deep Blue Sea. Tremors....",negative,pyramid clue deep blue sea tremor slither eigh...
1,0.5/10. This movie has absolutely nothing good...,negative,movi absolut noth good act among worst ever se...
2,"0*'s Christian Slater, Tara Reid, Stephen Dorf...",negative,christian slater tara reid stephen dorff frank...
3,"102 Dalmatians (2000, Dir. Kevin Lima) <br /><...",negative,dalmatian dir kevin lima believ cure cruella d...
4,102 DALMATIANS [Walt Disney]: I wasn't a fan o...,negative,dalmatian walt disney wasnt fan previou instal...

In [16]:
for i in range(5):
    
    print("=" * 80)
    
    print("REVIEW", i + 1)
    
    print("\nOriginal Review:")
    print(df["review"].iloc[i])
    
    print("\nCleaned Review:")
    print(df["cleaned_review"].iloc[i])
    
    print()

================================================================================
REVIEW 1

Original Review:
$25,000 Pyramid Clues: Deep Blue Sea. Tremors. Slither. Eight Legged Freaks.<br /><br />Pyramid Category: Movies that were funnier and more thrilling than Snakes on a Plane.<br /><br />Hell, with that definition I'd have to include the relatively harrowing journey of Ted and Elaine in Airplane! as superior to Snakes in both laughs and thrills.<br /><br />The sad truth is that this isn't even close to the mother of all unintentionally intentional funny snake movies: Anaconda! Besides the never to be seen again casting of JLo-Cube-O.Wilson-Stoltz-Wuhrer in the same flick, you had Jon Voight pulling off the all-time cinematic heist. His final scene alone represents everything SOAP tried and failed to do as a "so-ludicrous-it's-fun" movie.<br /><br />In the end, Snakes on a Plane is definitive proof that studio execs and fanboys make the worst collaborators possible. Every big scene had been discussed and dissected so much the last year, all that was left to amuse by opening night was the amount of fanboy flop-sweat that had to be mopped up at my theater. I heard more forced laughs here than at a studio taping for "According to Jim".

Cleaned Review:
pyramid clue deep blue sea tremor slither eight leg freak pyramid categori movi funnier thrill snake plane hell definit id includ rel harrow journey ted elain airplan superior snake laugh thrill sad truth isnt even close mother unintent intent funni snake movi anaconda besid never seen cast jlocubeowilsonstoltzwuhr flick jon voight pull alltim cinemat heist final scene alon repres everyth soap tri fail soludicrousitsfun movi end snake plane definit proof studio exec fanboy make worst collabor possibl everi big scene discuss dissect much last year left amus open night amount fanboy flopsweat mop theater heard forc laugh studio tape accord jim

================================================================================
REVIEW 2

Original Review:
0.5/10. This movie has absolutely nothing good about it. The acting is among the worst I have ever seen, what is really amazing is that EVERYONE is awful, not just a few here and there, everyone. The direction is a joke, the low budget is hopelessly evident, the score is awful, I wouldn't say the movie was edited, brutally chopped would be a more appropriate phrase. It combines serial killings, voodoo and tarot cards. Dumb. Dumb. Dumb. It is not scary at all, the special effects are hopelessly lame. laughably bad throughout. The writing was appallingly bad. The cinematography is real cheap looking, and very grainy sometimes, and the camera-work is dreadful. Again, what really does the movie in is how badly all the actors are. Cheesy.

Cleaned Review:
movi absolut noth good act among worst ever seen realli amaz everyon aw everyon direct joke low budget hopelessli evid score aw wouldnt say movi edit brutal chop would appropri phrase combin serial kill voodoo tarot card dumb dumb dumb scari special effect hopelessli lame laughabl bad throughout write appallingli bad cinematographi real cheap look graini sometim camerawork dread realli movi badli actor cheesi

================================================================================
REVIEW 3

Original Review:
0*'s Christian Slater, Tara Reid, Stephen Dorff, Frank C. Turner, Mathew Walker, Will Sanderson. Directed by Uwe Boll.<br /><br />Based on the video game director Uwe Boll attempts to recreate the game into an action-packed nail biter sadly he doesn't succeed. Instead he makes one of the worst movies ever MADE! Even though he gets minor celebrity such as Christian Slater, Tara Reid and Stephen Dorff his movie lacks the necessary fundamentals that a movie needs to be good such as a story line, and some basic relativity of what's going on in the dark and the light. The movie bounces all around and Uwe Boll has no creative control. And not to mention the bad CGI used on making the monsters. Even though they did look cool and the feedings were well, a little lame. Honestly this is one of the worst movies ever made. My final rating 0/10.

Cleaned Review:
christian slater tara reid stephen dorff frank c turner mathew walker sanderson direct uwe boll base video game director uwe boll attempt recreat game actionpack nail biter sadli doesnt succeed instead make one worst movi ever made even though get minor celebr christian slater tara reid stephen dorff movi lack necessari fundament movi need good stori line basic rel what go dark light movi bounc around uwe boll creativ control mention bad cgi use make monster even though look cool feed well littl lame honestli one worst movi ever made final rate

================================================================================
REVIEW 4

Original Review:
102 Dalmatians (2000, Dir. Kevin Lima) <br /><br />Believed to be cured, Cruella de Vil (Close) is released from prison and sets out to make a new start in life. Things are going well for Cruella who is busy helping homeless dogs off the street. When the clock strikes on Big Ben, things turn bad. The hypnotic cure is reversed and Cruella is back, and this time she is determined to make that spotted coat she always wanted.<br /><br />Glenn Close reprises her role as Cruella de Vil and once again is the highlight of the film. Every scene with her in is worth watching in this dull sequel, which feels more of a repeat of the previous film, rather than a new story.<br /><br />She's Changed.  Ken Sheperd (Ioan Gruffudd)

Cleaned Review:
dalmatian dir kevin lima believ cure cruella de vil close releas prison set make new start life thing go well cruella busi help homeless dog street clock strike big ben thing turn bad hypnot cure revers cruella back time determin make spot coat alway want glenn close repris role cruella de vil highlight film everi scene worth watch dull sequel feel repeat previou film rather new stori she chang ken sheperd ioan gruffudd

================================================================================
REVIEW 5

Original Review:
102 DALMATIANS [Walt Disney]: I wasn't a fan of the previous installment and this effort has all the weaknesses of the first, a silly padded storyline, terrible over acting by Glenn Close, who hams up every scene as though she's playing for her own amusement, and incredibly borring and uninteresting lead actors. Once more the dogs are the only "actors" that seem "real" and thats a stretch. Another wasted effort here. GRADE: D

Cleaned Review:
dalmatian walt disney wasnt fan previou instal effort weak first silli pad storylin terribl act glenn close ham everi scene though she play amus incred bor uninterest lead actor dog actor seem real that stretch anoth wast effort grade

In [17]:
final_df = df[
    ["review", "sentiment", "cleaned_review"]
]

final_df.head()

,review,sentiment,cleaned_review
0,"$25,000 Pyramid Clues: Deep Blue Sea. Tremors....",negative,pyramid clue deep blue sea tremor slither eigh...
1,0.5/10. This movie has absolutely nothing good...,negative,movi absolut noth good act among worst ever se...
2,"0*'s Christian Slater, Tara Reid, Stephen Dorf...",negative,christian slater tara reid stephen dorff frank...
3,"102 Dalmatians (2000, Dir. Kevin Lima) <br /><...",negative,dalmatian dir kevin lima believ cure cruella d...
4,102 DALMATIANS [Walt Disney]: I wasn't a fan o...,negative,dalmatian walt disney wasnt fan previou instal...

In [18]:
output_file = "preprocessed_IMDB_reviews.csv"

final_df.to_csv(
    output_file,
    index=False
)

print("Dataset exported successfully!")
print("File name:", output_file)

Dataset exported successfully!
File name: preprocessed_IMDB_reviews.csv

In [19]:
result = pd.read_csv("preprocessed_IMDB_reviews.csv")

print("Exported dataset loaded successfully!")

print("\nShape:")
print(result.shape)

print("\nColumns:")
print(result.columns.tolist())

print("\nFirst 5 rows:")
result.head()

Exported dataset loaded successfully!

Shape:
(49396, 3)

Columns:
['review', 'sentiment', 'cleaned_review']

First 5 rows:

,review,sentiment,cleaned_review
0,"$25,000 Pyramid Clues: Deep Blue Sea. Tremors....",negative,pyramid clue deep blue sea tremor slither eigh...
1,0.5/10. This movie has absolutely nothing good...,negative,movi absolut noth good act among worst ever se...
2,"0*'s Christian Slater, Tara Reid, Stephen Dorf...",negative,christian slater tara reid stephen dorff frank...
3,"102 Dalmatians (2000, Dir. Kevin Lima) <br /><...",negative,dalmatian dir kevin lima believ cure cruella d...
4,102 DALMATIANS [Walt Disney]: I wasn't a fan o...,negative,dalmatian walt disney wasnt fan previou instal...

In [20]:
print("=" * 60)
print("CUSTOMER REVIEW CLEANING SYSTEM")
print("=" * 60)

print("\nOriginal Dataset Size:")
print("50,000 reviews approximately")

print("\nFinal Dataset Size:")
print(len(final_df), "reviews")

print("\nColumns:")
for column in final_df.columns:
    print("-", column)

print("\nProcessing Steps Completed:")
print("✓ Dataset loaded using Pandas")
print("✓ Missing values checked")
print("✓ Duplicate reviews checked")
print("✓ Text converted to lowercase")
print("✓ HTML tags removed")
print("✓ URLs removed")
print("✓ Punctuation removed")
print("✓ Numbers removed")
print("✓ Special characters removed")
print("✓ Stopwords removed using NLTK")
print("✓ Reviews tokenized")
print("✓ Stemming applied")
print("✓ Cleaned review column created")
print("✓ Original and cleaned reviews compared")
print("✓ Dataset exported as CSV")

print("\nOutput File:")
print("preprocessed_IMDB_reviews.csv")

print("\nPROJECT COMPLETED SUCCESSFULLY!")

============================================================
CUSTOMER REVIEW CLEANING SYSTEM
============================================================

Original Dataset Size:
50,000 reviews approximately

Final Dataset Size:
49396 reviews

Columns:
- review
- sentiment
- cleaned_review

Processing Steps Completed:
✓ Dataset loaded using Pandas
✓ Missing values checked
✓ Duplicate reviews checked
✓ Text converted to lowercase
✓ HTML tags removed
✓ URLs removed
✓ Punctuation removed
✓ Numbers removed
✓ Special characters removed
✓ Stopwords removed using NLTK
✓ Reviews tokenized
✓ Stemming applied
✓ Cleaned review column created
✓ Original and cleaned reviews compared
✓ Dataset exported as CSV

Output File:
preprocessed_IMDB_reviews.csv

PROJECT COMPLETED SUCCESSFULLY!